name: Run Daily Random Fact Script

# This will run the workflow on a schedule (using cron syntax).
on:
  schedule:
    # Runs once every day at 8 AM CST / 9 AM CDT (2 PM UTC)
    - cron: '0 14 * * *'  # 2 PM UTC (which is 8 AM CST / 9 AM CDT)

# Define the jobs to run
jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the version you need

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Step 4: Run the Python script
      - name: Run daily_random_facts.py
        run: python daily_random_facts.py
